# Generated by Django 4.1.1 on 2023-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='User Email'),
        ),
    ]
